### ISSUE TITLE
Unable to validate step, invalid date.

### ISSUE THREAD

**Issue by Systemac** [Tkd-Alex/WeWard-Miner#1]
```
INFO - WeWard - [valid_step]: {'Host': 'backend.prod.weward.fr', 'user-agent': 'okhttp/4.9.1', 'content-type': 'application/json', 'ww_device_country': 'FR', 'ww_user_language': 'fr', 'authorization': 'autorisation....', 'ww_device_ts': '1646132127'}
 INFO - WeWard - [valid_step]: Veuillez ajuster la date de votre téléphone afin de procéder à la validation de vos pas.
 INFO - WeWard - [valid_step]: {'message': 'Veuillez ajuster la date de votre téléphone afin de procéder à la validation de vos pas.'}
```
in italiano : Regola la data sul tuo telefono per convalidare i tuoi passi.

After checking, the method update_request_timestamp gives the right date to the second... I don't really see where the problem comes from, knowing that it validates the ads without any problem and recovers all the other information...

Anyway, thanks for all the work :)

**Comment by Tkd-Alex** [comment]
The steps are pushed?

**Comment by Systemac** [comment]
Yes, i just use the step in readme : 
```
from WeWard import WeWard
weward = WeWard("xxxxx.json")
weward.push_step_record(25000)
weward.valid_step()
```

**Comment by Tkd-Alex** [comment]
uhm I need to investigate ...
It's so strange, I've created a thousand of accounts and they working smoothly 

I've tested also with the FR country, apparently the only difference between us

**Comment by Systemac** [comment]
i just test with another account, same here....
