### ISSUE TITLE
Login with an already existing account

### ISSUE THREAD

**Issue by Systemac** [Tkd-Alex/WeWard-Miner#2]
Is it possible to have the option to create a session from an existing account?

**Comment by Tkd-Alex** [comment]
Yup, I've facing this issue yesterday. I'll update the README asap
Basically, you can test the following

```python
weward.request_signin_with_email(email)
time.sleep(5)

url = weward.get_url_from_email(email, password)
while url is None:
    time.sleep(15)
    url = weward.get_url_from_email(email, password)

custom_token = weward.parse_token_from_url(url)

response = weward.google_verify_custom_token(custom_token)
# refresh_token = response["refreshToken"]
# response = weward.google_get_id_token(refresh_token)
id_token = response["id_token"]
session_path = weward.signin_with_id_token(id_token)

weward.load_session(session_path)
```

If you can't use a IMAP service, you can use 
```python
weward.request_signin_with_email(email)
```
![2022-03-06_12-56](https://user-images.githubusercontent.com/14061593/157032163-2050385d-7d74-4d3e-8fc4-8d3b7ac77962.png)

Get the link from the email and set in the variable `url`

**Comment by Systemac** [comment]
a yes thank you, it was precisely the imap that was blocking me, I will test that ;)

**Comment by Tkd-Alex** [comment]
If you are able to find the correct procedure, feel free to write here or submit a PR in the README

**Comment by Systemac** [comment]
PR Done.
