### ISSUE TITLE
when i start the script nothing happens

### ISSUE THREAD

**Issue by KAMLEGENDZ** [Tkd-Alex/WeWard-Miner#4]
![image](https://user-images.githubusercontent.com/86577993/161427815-c0a6f4a7-539f-469b-8eca-d8330b8366ec.png)

**Comment by Tkd-Alex** [comment]
You should pass the JSON file as second arguments

**Comment by KAMLEGENDZ** [comment]
how i do that

**Comment by Tkd-Alex** [comment]
Do you have some knowledge in python and scripting?

**Comment by KAMLEGENDZ** [comment]
nothing at all I'm a beginner

**Comment by KAMLEGENDZ** [comment]
what should i put in weward.valid_step

**Comment by Tkd-Alex** [comment]
> what should i put in weward.valid_step

Nothing

**Comment by KAMLEGENDZ** [comment]
ok i don't understand what i should do

**Comment by Tkd-Alex** [comment]
First of all; you have already generated a session file?

Do you want to create a new account or login with one that already own?

**Comment by KAMLEGENDZ** [comment]
i have the session file
i login to my account
![image](https://user-images.githubusercontent.com/86577993/161439533-fb143ef5-35af-46bb-b825-207821627ac4.png)

**Comment by KAMLEGENDZ** [comment]
bruh 
![image](https://user-images.githubusercontent.com/86577993/161815387-a39b35ce-19ca-4ff6-981c-b1e9a841dff9.png)

**Comment by KAMLEGENDZ** [comment]
in my json file ihave this
![image](https://user-images.githubusercontent.com/86577993/161816037-569dacaf-6d9e-4dae-9afe-30866369bb50.png)

**Comment by KAMLEGENDZ** [comment]
it works thanks
